name: boliches_sunmi
description: App Boliches Soft para Sunmi (caja + impresora)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sunmi_printer_plus: ^4.1.1
  supabase_flutter: ^2.5.0
  shared_preferences: ^2.2.0
  webview_flutter: ^4.7.0
  image: ^4.1.7

flutter:
  uses-material-design: true
